/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pc.remoto;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.InetAddress;
import java.net.NetworkInterface;
import java.net.SocketException;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author enaveira
 */
public class FormulaioInicial extends javax.swing.JFrame {
    
    private SocketServidor sc;
    private boolean pausa = false;
    
    /**
     * Creates new form FormulaioInicial
     */
    public FormulaioInicial() {
        initComponents();
        //setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icono.png")));
        Image image = new ImageIcon(getClass().getResource("/pc/remoto/img/icono.png")).getImage();
        setIconImage(image);
        
        sc=new SocketServidor();
        sc.start();
        
        this.setTitle(this.getTitle() + " - " + obtenerIP());
        //mostrarDatosConexion();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btDispositivo = new javax.swing.JButton();
        btCompartir = new javax.swing.JButton();
        btConfiguracion = new javax.swing.JButton();
        btCodigo = new javax.swing.JButton();
        btAutomatizar = new javax.swing.JButton();
        btPausar = new javax.swing.JButton();
        menu = new javax.swing.JMenuBar();
        mArchivo = new javax.swing.JMenu();
        mPlantillas = new javax.swing.JMenuItem();
        mConectar = new javax.swing.JCheckBoxMenuItem();
        mConfiguración = new javax.swing.JMenuItem();
        mSalir = new javax.swing.JMenuItem();
        mOpciones = new javax.swing.JMenu();
        mDispositivo = new javax.swing.JMenu();
        mUltimosDispositivos = new javax.swing.JMenuItem();
        mEnviarEnlace = new javax.swing.JMenuItem();
        mEnviarTexto = new javax.swing.JMenuItem();
        mEnviarCompartir = new javax.swing.JMenuItem();
        mAyuda = new javax.swing.JMenu();
        mAyudaItem = new javax.swing.JMenuItem();
        mVideo = new javax.swing.JMenuItem();
        mWeb = new javax.swing.JMenuItem();
        mCompartir = new javax.swing.JMenuItem();
        mAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PC Remoto");
        setBackground(new java.awt.Color(204, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(720, 500));
        setPreferredSize(new java.awt.Dimension(800, 600));

        btDispositivo.setBackground(new java.awt.Color(153, 255, 255));
        btDispositivo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btDispositivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pc/remoto/img/phone.png"))); // NOI18N
        btDispositivo.setText("Dispositivo");
        btDispositivo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btDispositivo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btCompartir.setBackground(new java.awt.Color(102, 255, 51));
        btCompartir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btCompartir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pc/remoto/img/conf.png"))); // NOI18N
        btCompartir.setText("Configuracion");
        btCompartir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCompartir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btConfiguracion.setBackground(new java.awt.Color(255, 51, 51));
        btConfiguracion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pc/remoto/img/share.png"))); // NOI18N
        btConfiguracion.setText("Compartir");
        btConfiguracion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btConfiguracion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfiguracionActionPerformed(evt);
            }
        });

        btCodigo.setBackground(new java.awt.Color(102, 102, 255));
        btCodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pc/remoto/img/qr.png"))); // NOI18N
        btCodigo.setText("Código de conexión");
        btCodigo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCodigo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCodigoActionPerformed(evt);
            }
        });

        btAutomatizar.setBackground(new java.awt.Color(255, 255, 51));
        btAutomatizar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btAutomatizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pc/remoto/img/robot.png"))); // NOI18N
        btAutomatizar.setText("Automatizar");
        btAutomatizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAutomatizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btAutomatizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAutomatizarActionPerformed(evt);
            }
        });

        btPausar.setBackground(new java.awt.Color(255, 102, 51));
        btPausar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btPausar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pc/remoto/img/on.png"))); // NOI18N
        btPausar.setText("Pausar");
        btPausar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPausar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPausarActionPerformed(evt);
            }
        });

        mArchivo.setText("Archivo");

        mPlantillas.setText("Plantillas");
        mArchivo.add(mPlantillas);

        mConectar.setSelected(true);
        mConectar.setText("Conectar");
        mConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mConectarActionPerformed(evt);
            }
        });
        mArchivo.add(mConectar);

        mConfiguración.setText("Configuración");
        mArchivo.add(mConfiguración);

        mSalir.setText("Salir");
        mArchivo.add(mSalir);

        menu.add(mArchivo);

        mOpciones.setText("Opciones");
        menu.add(mOpciones);

        mDispositivo.setText("Dispositivo");

        mUltimosDispositivos.setText("Ultimos dispositivos");
        mDispositivo.add(mUltimosDispositivos);

        mEnviarEnlace.setText("Enviar enlace");
        mDispositivo.add(mEnviarEnlace);

        mEnviarTexto.setText("Enviar texto");
        mEnviarTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEnviarTextoActionPerformed(evt);
            }
        });
        mDispositivo.add(mEnviarTexto);

        mEnviarCompartir.setText("Enviar y compartir");
        mDispositivo.add(mEnviarCompartir);

        menu.add(mDispositivo);

        mAyuda.setText("Ayuda");

        mAyudaItem.setText("Ayuda");
        mAyuda.add(mAyudaItem);

        mVideo.setText("Video manual");
        mAyuda.add(mVideo);

        mWeb.setText("Pagina web");
        mAyuda.add(mWeb);

        mCompartir.setText("Compartir programa");
        mAyuda.add(mCompartir);

        mAcerca.setText("Acerca de");
        mAyuda.add(mAcerca);

        menu.add(mAyuda);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btAutomatizar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDispositivo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btConfiguracion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCompartir, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPausar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCompartir, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDispositivo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAutomatizar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPausar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btAutomatizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAutomatizarActionPerformed

    }//GEN-LAST:event_btAutomatizarActionPerformed

    private void btPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPausarActionPerformed
        botonConectado();
    }//GEN-LAST:event_btPausarActionPerformed

    private void mEnviarTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mEnviarTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mEnviarTextoActionPerformed

    private void btCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCodigoActionPerformed
        mostrarDatosConexion();
    }//GEN-LAST:event_btCodigoActionPerformed

    private void btConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfiguracionActionPerformed
        String resultado = JOptionPane.showInputDialog("Introduce elemento a compartir con el dispositivo actual:");
        System.out.println(resultado);
    }//GEN-LAST:event_btConfiguracionActionPerformed

    private void mConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mConectarActionPerformed
        botonConectado();
    }//GEN-LAST:event_mConectarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormulaioInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormulaioInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormulaioInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormulaioInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormulaioInicial().setVisible(true);
            }
        });
    }
    
    private String obtenerIP(){
        
        String listaIP = "";
        
        try {
            
            Enumeration e = NetworkInterface.getNetworkInterfaces();
            while (e.hasMoreElements()) {
                NetworkInterface n = (NetworkInterface) e.nextElement();
                Enumeration ee = n.getInetAddresses();
                while (ee.hasMoreElements()) {
                    InetAddress i = (InetAddress) ee.nextElement();
                    //System.out.println(i.getHostAddress());
                    String iptemp=i.getHostAddress();
                    if(!(i.getHostAddress().contains(":")||i.getHostAddress().equals("127.0.0.1"))){
                        listaIP += i.getHostAddress() + ";";
                    }
                }
            }
        } catch (SocketException ex) {
            Logger.getLogger(FormulaioInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        return listaIP;
    }
    
    private void mostrarDatosConexion(){
        String ips = obtenerIP();
        ImageIcon codigoQR = new GeneradorQR().generar(ips);
        
        ips = ips.replace(";", "<br>");//remplazamos la división anterior de ; a cambio de linea
        ips = "<html><h2>Direccion IP: <br>" + ips + "<h2></html>";
        
        JLabel etiqueta = new JLabel(ips, codigoQR, JLabel.CENTER);
        etiqueta.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        etiqueta.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);
        
        JOptionPane.showMessageDialog(null,etiqueta,"Información de conexión", JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void botonConectado(){
        if (pausa){
            pausa = false;
            btPausar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pc/remoto/img/on.png")));
            sc.reanudar();
            mConectar.setState(!pausa);
        }else{
            pausa = true;
            btPausar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pc/remoto/img/off.png")));
            sc.pausar();
            mConectar.setState(!pausa);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAutomatizar;
    private javax.swing.JButton btCodigo;
    private javax.swing.JButton btCompartir;
    private javax.swing.JButton btConfiguracion;
    private javax.swing.JButton btDispositivo;
    private javax.swing.JButton btPausar;
    private javax.swing.JMenuItem mAcerca;
    private javax.swing.JMenu mArchivo;
    private javax.swing.JMenu mAyuda;
    private javax.swing.JMenuItem mAyudaItem;
    private javax.swing.JMenuItem mCompartir;
    private javax.swing.JCheckBoxMenuItem mConectar;
    private javax.swing.JMenuItem mConfiguración;
    private javax.swing.JMenu mDispositivo;
    private javax.swing.JMenuItem mEnviarCompartir;
    private javax.swing.JMenuItem mEnviarEnlace;
    private javax.swing.JMenuItem mEnviarTexto;
    private javax.swing.JMenu mOpciones;
    private javax.swing.JMenuItem mPlantillas;
    private javax.swing.JMenuItem mSalir;
    private javax.swing.JMenuItem mUltimosDispositivos;
    private javax.swing.JMenuItem mVideo;
    private javax.swing.JMenuItem mWeb;
    private javax.swing.JMenuBar menu;
    // End of variables declaration//GEN-END:variables
}
